// Generated by scripts/sync-skills.mjs. Do not hand-edit; run `npm run sync:skills`.
// The commit the bundled skill content was vendored from, for a shell to show
// beside a bundled repo. `tag` is a label only; the commit is the pin.
export const SKILLS_PIN = {
  repo: "galaxyproject/agentic-plugins",
  commit: "aa4da4bd68eb00e360dfd5aa6e998feb5de0ac49",
  commitDate: "2026-09-17",
  tag: null,
};
