// Generated by scripts/sync-skills.mjs. Do not hand-edit; run `npm run sync:skills`.
export const SKILLS_PIN: {
  repo: string;
  /** Commit the bundled content was vendored from. Tags move; this does not. */
  commit: string;
  commitDate: string | null;
  tag: string | null;
};
